// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTxwDCYzvmieXud0mwkSK5aBr8_BpIas',
    appId: '1:567172814992:web:da48be9af3905b01c8a015',
    messagingSenderId: '567172814992',
    projectId: 'social-link-app-aa5ff',
    authDomain: 'social-link-app-aa5ff.firebaseapp.com',
    storageBucket: 'social-link-app-aa5ff.appspot.com',
    measurementId: 'G-QBJS3MSXJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6ShLRErmyWzA3u4ZPWnEVIENlPiaDu0',
    appId: '1:567172814992:android:c897a390f75bb75ac8a015',
    messagingSenderId: '567172814992',
    projectId: 'social-link-app-aa5ff',
    storageBucket: 'social-link-app-aa5ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhI5siRvnEeelCYA8uFQ7DbxYJHVFWuKk',
    appId: '1:567172814992:ios:fb9a20e5ade9a84dc8a015',
    messagingSenderId: '567172814992',
    projectId: 'social-link-app-aa5ff',
    storageBucket: 'social-link-app-aa5ff.appspot.com',
    iosBundleId: 'com.example.socialLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhI5siRvnEeelCYA8uFQ7DbxYJHVFWuKk',
    appId: '1:567172814992:ios:37649049c9d2e3a3c8a015',
    messagingSenderId: '567172814992',
    projectId: 'social-link-app-aa5ff',
    storageBucket: 'social-link-app-aa5ff.appspot.com',
    iosBundleId: 'com.example.socialLinkApp.RunnerTests',
  );
}
